flag:
  COLDSTART: 'YES'
  IC_FROM_FIX_DIR: 'YES'
  JEDI_TYPE_SNOW: 'YES'
  JEDI_TYPE_SOCA: 'NO'
  JEDI_TYPE_SOIL_MOISTURE: 'NO'
  OBS_SNOW_GHCN: 'YES' 
path:
parm:
  ACCOUNT: epic
  APP: S2SWA
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2021032206
  DATE_LAST_CYCLE: 2021032306
  DT_ATMOS: 720
  DT_RUNSEQ: 3600
  envir: s2swa_snowDA_letkfoi_ecf
  EXP_CASE_NAME: s2swa_snowDA_letkfoi_ecf
  FCST_HRS: 24
  JEDI_ALGORITHM: letkf-oi
  OUTPUT_FH: '6 -1'
  WORKFLOW_MANAGER: ecflow
