flag:
  COLDSTART: 'NO'
  IC_FROM_FIX_DIR: 'NO'
  JEDI_TYPE_SNOW: 'YES'
  JEDI_TYPE_SOCA: 'NO'
  JEDI_TYPE_SOIL_MOISTURE: 'NO'
  OBS_SNOW_GHCN: 'YES'
path:
parm:
  ACCOUNT: epic
  APP: S2SWAL
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2021032218
  DATE_LAST_CYCLE: 2021032218
  DT_ATMOS: 720
  DT_RUNSEQ: 3600
  envir: s2swal_snowDA_letkfoi_ecf
  EXP_CASE_NAME: s2swal_snowDA_letkfoi_ecf
  FCST_HRS: 24
  JEDI_ALGORITHM: letkf-oi
  NPROCS_WAV: 20
  OUTPUT_FH: '6 -1'
  WORKFLOW_MANAGER: ecflow
