flag:
  COLDSTART: 'YES'
  IC_FROM_FIX_DIR: 'NO'
  JEDI_TYPE_SNOW: 'YES'
  JEDI_TYPE_SOCA: 'NO'
  JEDI_TYPE_SOIL_MOISTURE: 'NO'
  OBS_SNOW_GHCN: 'YES' 
path:
parm:
  ACCOUNT: epic
  APP: ATML
  CCPP_SUITE: FV3_GFS_v17_p8_ugwpv1
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2025012000
  DATE_LAST_CYCLE: 2025012100
  DT_ATMOS: 720
  DT_RUNSEQ: 720
  envir: atml_snowDA_letkfoi_ecf
  EXP_CASE_NAME: atml_snowDA_letkfoi_ecf
  FCST_HRS: 24
  IC_DATA_MODEL: gfs
  JEDI_ALGORITHM: letkf-oi
  OUTPUT_FH: '6 -1'
  WORKFLOW_MANAGER: ecflow
