flag:
  COLDSTART: 'YES'
  FRAC_GRID: 'NO'
  IC_FROM_FIX_DIR: 'YES'
  JEDI_TYPE_SNOW: 'NO'
  JEDI_TYPE_SOCA: 'NO'
  JEDI_TYPE_SOIL_MOISTURE: 'YES'
  OBS_SWC_SMOPS: 'YES'
path:
parm:
  ACCOUNT: epic
  APP: ATML
  CCPP_SUITE: FV3_GFS_v17_p8_ugwpv1
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2021032206
  DATE_LAST_CYCLE: 2021032306
  DT_ATMOS: 720
  DT_RUNSEQ: 3600
  envir: atml_soilmDA_letkfoi
  EXP_CASE_NAME: atml_soilmDA_letkfoi
  FCST_HRS: 48
  IC_DATA_MODEL: gfs
  JEDI_ALGORITHM: letkf-oi
  OUTPUT_FH: '12 -1'
  TYPE_ANAL_FCST: fcst-1st
  WALLTIME_FORECAST: '00:30:00'
  WORKFLOW_MANAGER: rocoto
