flag:
  COLDSTART: 'YES'
  IC_FROM_FIX_DIR: 'YES'
  JEDI_TYPE_SNOW: 'NO'
  JEDI_TYPE_SOCA: 'NO'
  JEDI_TYPE_SOIL_MOISTURE: 'YES'
  OBS_SWC_SMOPS: 'YES'
path:
parm:
  ACCOUNT: epic
  APP: S2SWA
  DATE_CYCLE_FREQ_HR: 24
  DATE_FIRST_CYCLE: 2021032206
  DATE_LAST_CYCLE: 2021032406
  DT_ATMOS: 720
  DT_RUNSEQ: 3600
  envir: soilmDA_letkfoi
  EXP_CASE_NAME: s2swa_soilmDA_letkfoi
  FCST_HRS: 48
  JEDI_ALGORITHM: letkf-oi
  OUTPUT_FH: '12 -1'
  TYPE_ANAL_FCST: fcst-1st
  WALLTIME_FORECAST: '01:00:00'
