flag:
  CUSTOM_JEDI_CONFIG_FLAG: 'TEMPLATE'
  JEDI_TYPE_FV3: 'YES'
  JEDI_TYPE_SNOW: 'NO'
  JEDI_TYPE_SOCA: 'NO'
  OBS_ATM_AMV_ABI_GOES_16: 'NO'
  OBS_ATM_ASCAT_W: 'NO'
  OBS_ATM_ATMS_N20: 'NO'
  OBS_ATM_CONVENTIONAL_PS: 'YES'
  OBS_ATM_GNSSRO_COSMIC2: 'YES'
  OBS_ATM_OZONE_OMPSNP_NPP: 'NO'
  OBS_ATM_OZONE_OMPSTC_NPP: 'NO'
path:
parm:
  ACCOUNT: epic
  DATE_CYCLE_FREQ_HR: 6
  DATE_FIRST_CYCLE: 2024022400
  DATE_LAST_CYCLE: 2024022400
  ENSEMBLE_NUM_MEMBERS: 2
  envir: anal_atmDA_3dvar_ecf
  EXP_CASE_NAME: anal_atmDA_3dvar_ecf
  JEDI_ALGORITHM: 3dvar
  JEDI_BUNDLE_GDAS: gdas
  NPROCS_ANALYSIS: 96
  TYPE_ANAL_FCST: anal-only  
  WORKFLOW_MANAGER: ecflow
